Decorator retry
AlexGrig23/Python-project pull request #15
Opened 2023-03-22 11:02 UTC by AlexGrig23

2023-03-29 09:48 UTC, vladyslavushakovten requested changes
Рішення невірне

2023-03-29 09:48 UTC, vladyslavushakovten commented on retry_decor.py
> +def decorator(func, exc="Too many error", max_retries=3):
ТАк не працює, декоратор з параметрами не так створюється

2023-03-29 09:48 UTC, vladyslavushakovten commented on retry_decor.py
> +                print(exc)
Помилку не прінтять а raise потрібно виконувати

2023-04-10 14:36 UTC, vladysllav requested changes
Залишив коментарі

2023-04-10 14:36 UTC, vladysllav commented on retry_decor.py
> +                if i == max_retries:
Навіщо і тут і там робити перевірку, ти ж вже робиш таку саму перевірку у циклі

2023-04-10 14:36 UTC, vladysllav commented on retry_decor.py
> +                    raise ZeroDivisionError(exc)
Чому саме таку помилку райзиш, ідея у тому зо exc - це буде як раз таки помилка типу Exception or TypeError, а не текст помилки. тому по факту потрібно буде робити raise exc

2023-04-10 14:36 UTC, vladysllav commented on retry_decor.py
> +                except ZeroDivisionError as ex:
Чому ти тільки цю помилку відловлюєшь, а всі інші?

2023-04-19 13:54 UTC, vladysllav approved these changes

2023-05-02 08:08 UTC, merged