Combination generator
AlexGrig23/Python-project pull request #21
Opened 2023-04-01 15:53 UTC by AlexGrig23

2023-04-08 06:26 UTC, vladyslavushakovten requested changes
Не вірний генератор

2023-04-08 06:26 UTC, vladyslavushakovten commented on combination_generator.py
> +    yield permutations
Ти одразу повертаєшь все, а потрібно по одному

2023-04-12 13:22 UTC, AlexGrig23 commented
В задаче просто они комбинации написаны в рядок, я думал что все сразу надо вывести. Переделал.

2023-04-19 13:54 UTC, vladysllav approved these changes

2023-05-02 08:09 UTC, merged